name: Test
on: [pull_request]
jobs:
  haml-lint:
    name: runner / haml-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
      - name: github-pr-check with workdir
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          workdir: ./testdata/subdir/
      - name: github-pr-review with extra flags
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          haml_lint_flags: -c ./testdata/.haml-lint.yml
          reviewdog_flags: -filter-mode=file -fail-on-error
      - name: github-pr-review with rubocop version
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          haml_lint_flags: -c ./testdata/.haml-lint.yml
          rubocop_version: 1.31.2
